export const TEMPLATE_POST =[
    {
        id:0,
        url_demo:'http://anbinhnew.com/demo_tempalte_0'
    },
    {
        id:1,
        url_demo:'http://anbinhnew.com/demo_tempalte_1'
    },
    {
        id:2,
        url_demo:'http://anbinhnew.com/demo_tempalte_2'
    },
];
export const TEMPLATE_CATEGORY =[
    {
        id:0,
        url_demo:'http://anbinhnew.com/demo_tempalte_0'
    },
    {
        id:1,
        url_demo:'http://anbinhnew.com/demo_tempalte_1'
    },
    {
        id:2,
        url_demo:'http://anbinhnew.com/demo_tempalte_2'
    },
];
export const TEMPLATE_PAGE =[
    {
        id:0,
        url_demo:'http://anbinhnew.com/demo_tempalte_0'
    },
    {
        id:1,
        url_demo:'http://anbinhnew.com/demo_tempalte_1'
    },
    {
        id:2,
        url_demo:'http://anbinhnew.com/demo_tempalte_2'
    },
];